#pragma config(Sensor, port7,  gyo,            sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          left,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          right,         tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         arm,           tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         claw,          tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void gyroright(int turny)
{
	turny = -turny;
		resetGyro(gyo);
	while(getGyroDegreesFloat(gyo)>turny)//the limit is -85 degrees
	{//Turning right
		setMotorSpeed(left, getGyroDegreesFloat(gyo) - turny + 10 );//left motor is going forward
		setMotorSpeed(right, -( getGyroDegreesFloat(gyo) - turny + 10 ));//right motor is going backwards
	}
		setMotorSpeed(left, 0);
		setMotorSpeed(right, 0);
		wait1Msec(1000);
}

void gyroleft(int turny)
{
		resetGyro(gyo);
	while(getGyroDegreesFloat(gyo)<turny)//the limit is -85 degrees
	{//Turning right
		setMotorSpeed(left, -(getGyroDegreesFloat(gyo) - -360 + 5 ));//left motor is going forward
		setMotorSpeed(right, ( getGyroDegreesFloat(gyo) - -360 + 5 ));//right motor is going backwards
	}
		setMotorSpeed(left, 0);
		setMotorSpeed(right, 0);
		wait1Msec(1000);
}

task main()
{
	setMotorTarget(left, 1000, 100);
	setMotorTarget(right, 1000, 100);
	waitUntilMotorStop(left);
	waitUntilMotorStop(right);

	gyroleft(90);


	resetMotorEncoder(left);
	resetMotorEncoder(right);
	setMotorTarget(left, 950, 100);
	setMotorTarget(right, 950, 100);
	waitUntilMotorStop(left);
	waitUntilMotorStop(right)





}
