#pragma config(Sensor, port4,  distance,       sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          left,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          right,         tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forwardDistance(int dist)
{
	int speed = 100;
	while(getDistanceValue(distance)>dist)//the limit is -85 degrees
	{//Turning right
		speed = getDistanceValue(distance) - dist;
		setMotorSpeed(left, speed );//left motor is going forward
		setMotorSpeed(right, speed);//right motor is going backwards
	}
		setMotorSpeed(left, 0);
		setMotorSpeed(right, 0);
		wait1Msec(1000);
}


task main()
{
	forwardDistance(184);
	wait1Msec(3000);
	forwardDistance(100);
}
