#pragma config(Sensor, port2,  compass,        sensorVexIQ_Gyro)
#pragma config(Sensor, port3,  pitch,          sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          motorleft,     tmotorNone, openLoop)
#pragma config(Motor,  motor6,          motorright,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, port3,  distancesensor, sensorVexIQ_Distance)
task main()
{
//	Once you get the distance sensor you can un comment all the code
//

//	while(getDistanceValue(distancesensor)>190)
//	{
//		setMotorSpeed(motorleft, 95);
//		setMotorSpeed(motorright, 100);
//	}

//	setMotorSpeed(motorleft, 0);
//	setMotorSpeed(motorright, 0);
//	wait1Msec(1000);


	resetGyro(compass);
	while(getGyroDegreesFloat(compass)>-360)//the limit is -85 degrees
	{//Turning right
		setMotorSpeed(motorleft, getGyroDegreesFloat(compass) - -360 + 5 );//left motor is going forward
		setMotorSpeed(motorright, -( getGyroDegreesFloat(compass) - -360 + 5 ));//right motor is going backwards
	}
		setMotorSpeed(motorleft, 0);
		setMotorSpeed(motorright, 0);
		wait1Msec(1000);	//Stop motors

   //do this for 1 second

//	while(getDistanceValue(distancesensor)>190)
//	{
//		setMotorSpeed(motorleft, 62);
//		setMotorSpeed(motorright, 65);
//	}


}
